name: schedule

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  send_to_channels:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}
      CHANNEL_ID_1: ${{ secrets.CHANNEL_ID_1 }}
      CHANNEL_ID_2: ${{ secrets.CHANNEL_ID_2 }}

    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: yarn install

      - name: Run Command
        run: yarn start
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHANNEL_ID_1: ${{ secrets.CHANNEL_ID_1 }}
          CHANNEL_ID_2: ${{ secrets.CHANNEL_ID_2 }}
